openapi: 3.0.0
info:
  title: Notification Service
  version: 1.0.0

servers:
  - url: http://localhost:3000

paths:
  /notifications:
    post:
      tags:
        - 'Notifications'
      summary: Send a notification to a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                company_id:
                  type: string
                  example: 123
                user_id:
                  type: string
                  example: 456
                notification_type:
                  type: string
                  enum:
                    - leave-balance-reminder
                    - monthly-payslip
                    - happy-birthday

      responses:
        201:
          description: OK
        400:
          description: Bad Request
        500:
          description: Internal Server Error
